#!/usr/bin/env bash
# Allow root/admin users to do everything
# Deny access to default users
# Allow access for deployment

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

# echo "Verifying user authorization for: $SSH_USER | $SSH_NAME"

SSH_USER=$1
SSH_NAME=$2
shift 2

# echo "Command: $1"
# echo "$1"
echo "$SSH_NAME"

[[ "$SSH_USER" == "root" ]] && exit 0
[[ "$SSH_NAME" == "admin" ]] && exit 0

# [[ "$SSH_USER" == "dokku" ]] && exit 1
[[ "$SSH_NAME" == "default" ]] && exit 1

# Allow Deploys
[[ "$SSH_USER" == "dokku" && $1 == git* ]] && exit 1
[[ "$SSH_USER" == "dokku" && $1 == git-hook ]] && exit 1
[[ "$SSH_USER" == "dokku" && $1 == git-upload-pack ]] && exit 1

echo "$1"

# echo "Limited users may only deploy and manage their own apps."

exit 1
