#!/usr/bin/env bash
# Allow root/admin users to do everything
# Deny access to default users
# Allow access for dokku user to perform specific actions if whitelisted

# source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

# Debug
SSH_USER=$1
SSH_NAME=$2
# shift 2

# echo "Verifying user authorization for: $SSH_USER | $SSH_NAME for command $3"
# echo "$1 $2 $3 $4 $5 $DOKKU_APP_NAME"

# Root and admin users have full access
[[ "$SSH_USER" == "root" ]] && exit 0
[[ "$SSH_NAME" == "admin" ]] && exit 0
[[ "$SSH_NAME" == "ledokku" ]] && exit 0

# Default users can do nothing
[[ "$SSH_NAME" == "default" ]] && exit 1

# Whitelist a specific set of users defined in the env DOKKU_ALLOWED_USERS
if ([[ $DOKKU_APP_NAME ]])
  then
    ALLOWED_USERS=$(config_get $DOKKU_APP_NAME "DOKKU_ALLOWED_USERS")
    # echo "$ALLOWED_USERS"

    # If we have an app name and user make sure its a whitelisted user
    [[ ! $ALLOWED_USERS =~ $SSH_NAME ]] && exit 1
fi

# Prevent certain flags from being passed to any command
[[ $* == *--rm-container* ]] && exit 1
[[ $* == *--global* ]] && exit 1
[[ $* == *--trace* ]] && exit 1
[[ $* == *--force* ]] && exit 1
[[ $* == *--rm* ]] && exit 1

# Allow Deploys from dokku user
[[ "$SSH_USER" == "dokku" && $3 == git* ]] && exit 0
[[ "$SSH_USER" == "dokku" && $3 == git-hook ]] && exit 0
[[ "$SSH_USER" == "dokku" && $3 == git-upload-pack ]] && exit 0

# Allow dokku logs
[[ "$SSH_USER" == "dokku" && $3 == logs ]] && exit 0

# Allow users to set config
[[ "$SSH_USER" == "dokku" && $3 == config* ]] && exit 0

# Prevent execution of global domain commands
[[ "$SSH_USER" == "dokku" && $3 == domains:add-global ]] && exit 1
[[ "$SSH_USER" == "dokku" && $3 == domains:clear-global ]] && exit 1
[[ "$SSH_USER" == "dokku" && $3 == domains:remove-global ]] && exit 1
[[ "$SSH_USER" == "dokku" && $3 == domains:set-global ]] && exit 1
[[ "$SSH_USER" == "dokku" && $3 == domains:enable ]] && exit 1
[[ "$SSH_USER" == "dokku" && $3 == domains:disable ]] && exit 1

# Allow all other domain commands
[[ "$SSH_USER" == "dokku" && $3 == domains:* ]] && exit 0

# Allow App start / stop / restarts / restart policy / report
[[ "$SSH_USER" == "dokku" && $3 == ps:report ]] && exit 0
[[ "$SSH_USER" == "dokku" && $3 == ps:rebuild ]] && exit 0
[[ "$SSH_USER" == "dokku" && $3 == ps:restart ]] && exit 0
[[ "$SSH_USER" == "dokku" && $3 == ps:start ]] && exit 0
[[ "$SSH_USER" == "dokku" && $3 == ps:stop ]] && exit 0
[[ "$SSH_USER" == "dokku" && $3 == ps:set-restart-policy ]] && exit 0
[[ "$SSH_USER" == "dokku" && $3 == ps:restart-policy ]] && exit 0

# Allow certs commands
[[ "$SSH_USER" == "dokku" && $3 == certs:* ]] && exit 0

# Allow let's encrypt
[[ "$SSH_USER" == "dokku" && $3 == letsencrypt ]] && exit 0

# Allow resource report resource:report
[[ "$SSH_USER" == "dokku" && $3 == resource:report ]] && exit 0

# Allow users to dokku enter
[[ "$SSH_USER" == "dokku" && $3 == enter ]] && exit 0

# Help Text

if ([[ "$SSH_USER" == "dokku" && $3 == "" || $3 == "help" ]])
  then
    echo " "
    echo "------------------------------------------------------------"
    echo "    Welcome! You are currently in a limited Dokku session."
    echo "------------------------------------------------------------"
    echo " "
    echo " "
    echo "    You can deploy your app by creating a Git remote, and "
    echo "    running 'git push dokku master' or 'git push dokku main:master'"
    echo " "
    echo " "
    echo "------------------------------------------------------------------------------------------------------------------------"
    echo "    Full List of Commands:"
    echo "------------------------------------------------------------------------------------------------------------------------"
    echo " "
    echo " "
    echo "------------------------------------------------------------------------------------------------------------------------"
    echo "    Logs:"
    echo "------------------------------------------------------------------------------------------------------------------------"
    echo " "
    echo "    dokku logs                                          See the latest logs for the current app"
    echo " "
    echo " "
    echo "------------------------------------------------------------------------------------------------------------------------"
    echo "    Application Management:"
    echo "------------------------------------------------------------------------------------------------------------------------"
    echo " "
    echo "    dokku ps:start                                      Start app container"
    echo "    dokku ps:stop                                       Stop app container"
    echo "    dokku ps:restart                                    Restart app container"
    echo "    dokku ps:rebuild                                    Rebuild an app from source"
    echo "    dokku ps:report                                     Displays a process report for the current app"
    echo "    dokku ps:restart-policy                             Shows the restart-policy for the current app"
    echo "    dokku ps:set-restart-policy <policy>                Sets app restart-policy"
    echo "    dokku enter                                         Enter the docker container (Interactive)"
    echo " "
    echo " "
    echo "------------------------------------------------------------------------------------------------------------------------"
    echo "    SSL & Resource Allocation:"
    echo "------------------------------------------------------------------------------------------------------------------------"
    echo " "
    echo "    dokku letsencrypt                                   Enables SSL via Let's Encrypt"
    echo "    dokku resource:report                               Displays a resource report for the current app"
    echo " "
    echo " "
    echo "------------------------------------------------------------------------------------------------------------------------"
    echo "    Domains:"
    echo "------------------------------------------------------------------------------------------------------------------------"
    echo " "
    echo "    dokku domains:add <domain> [<domain> ...]           Add domain(s) to app"
    echo "    dokku domains:clear                                 Clear all domains for app"
    echo "    dokku domains:remove <domain> [<domain> ...]        Remove domains from app"
    echo "    dokku domains:report                                Displays a domains report for your current app"
    echo "    dokku domains:set <app> <domain> [<domain> ...]     Set domains for app"
    echo " "
    echo " "
    echo "------------------------------------------------------------------------------------------------------------------------"
    echo "    Environment Variables:"
    echo "------------------------------------------------------------------------------------------------------------------------"
    echo " "
    echo "    dokku config                                                                Pretty-print an app or global environment"
    echo "    dokku config:clear [--no-restart]                                           Clears environment variables"
    echo "    dokku config:get [--quoted] KEY                                             Display a global or app-specific config value"
    echo "    dokku config:keys [--merged]                                                Show keys set in environment"
    echo "    dokku config:show [--merged]                                                Show keys set in environment"
    echo "    dokku config:set [--encoded] [--no-restart]  KEY1=VALUE1 [KEY2=VALUE2 ...]  Set one or more config vars"
    echo "    dokku config:unset [--no-restart]  KEY1 [KEY2 ...]                          Unset one or more config vars"

    echo " "
    echo " "
    echo "------------------------------------------------------------------------------------------------------------------------"
    echo " "
fi


##############################
# Exit, prohibiting all other commands
##############################
# echo "$3"
# echo "Limited users may only deploy and manage their own apps."

exit 1
