#!/usr/bin/env bash
# Allow root/admin users to do everything
# Deny access to default users
# Allow access for deployment

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

# Debug
# echo "Verifying user authorization for: $SSH_USER | $SSH_NAME for command $3"

SSH_USER=$1
SSH_NAME=$2
# shift 2

# Root and admin users have full access
[[ "$SSH_USER" == "root" ]] && exit 0
[[ "$SSH_NAME" == "admin" ]] && exit 0

# Default users can do nothing
[[ "$SSH_NAME" == "default" ]] && exit 1

# Allow Deploys from dokku user
[[ "$SSH_USER" == "dokku" && $3 == git* ]] && exit 0
[[ "$SSH_USER" == "dokku" && $3 == git-hook ]] && exit 0
[[ "$SSH_USER" == "dokku" && $3 == git-upload-pack ]] && exit 0

# echo "$3"
# echo "Limited users may only deploy and manage their own apps."

# Prohibit all other commands
exit 1
